"use client";

import { useEffect, useState } from "react";

import styles from "@/components/accountant-v3/WorkflowBridge.module.css";

type Props = { admin: { id: string; name: string; email: string }; dashboardHref?: string };

function Icon({ name }: { name: string }) { return <span className="material-symbols-rounded">{name}</span>; }
function money(value: unknown) { return new Intl.NumberFormat("en-TZ", { style:"currency", currency:"TZS", maximumFractionDigits:0 }).format(Number(value??0)); }
async function json<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:"include",cache:"no-store",...options});const text=await response.text();const result=text?JSON.parse(text):{};if(!response.ok||result.success===false)throw new Error(result.message||`Request failed (${response.status}).`);return result as T;}
async function upload(file:File){const form=new FormData();form.append("file",file);return json<{success:true;url:string}>("/api/accountant-v3/uploads",{method:"POST",body:form});}

export default function CompanyAdminAccountantBridgeClient({ admin, dashboardHref = "/company-admin/dashboard" }: Props) {
  const [data,setData]=useState<any>({packets:[],expenses:[],bankComparisons:[],devices:[],staff:[]});
  const [busy,setBusy]=useState(false);
  const [toast,setToast]=useState("");
  const [packetRefs,setPacketRefs]=useState<Record<string,{message:string;url:string}>>({});
  const [expenseReasons,setExpenseReasons]=useState<Record<string,string>>({});
  const [bankRefs,setBankRefs]=useState<Record<string,{adminAmount:string;adminReference:string;adminDate:string;adminBankAccount:string;adminFileUrl:string}>>({});
  const [device,setDevice]=useState({name:"",serialNumber:"",locationLabel:""});
  const [enrollment,setEnrollment]=useState({deviceId:"",staffId:"",templateKey:""});

  useEffect(()=>{void load();},[]);
  async function load(){try{setData(await json("/api/company-admin/accountant-bridge"));}catch(error){setToast(error instanceof Error?error.message:"Could not load bridge data.");}}
  async function act(action:string,payload:Record<string,unknown>){setBusy(true);try{const result:any=await json("/api/company-admin/accountant-bridge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});setToast(result.message);await load();return result;}catch(error){setToast(error instanceof Error?error.message:"Action failed.");return null;}finally{setBusy(false);}}
  async function fileChange(file:File|undefined,key:string,type:"packet"|"bank"){if(!file)return;setBusy(true);try{const result=await upload(file);if(type==="packet"){const current=packetRefs[key]??{message:"",url:""};setPacketRefs({...packetRefs,[key]:{...current,url:result.url}});}else{const current=bankRefs[key]??{adminAmount:"",adminReference:"",adminDate:new Date().toISOString().slice(0,10),adminBankAccount:"",adminFileUrl:""};setBankRefs({...bankRefs,[key]:{...current,adminFileUrl:result.url}});}setToast("Reference file uploaded.");}catch(error){setToast(error instanceof Error?error.message:"Upload failed.");}finally{setBusy(false);}}

  return <main className={styles.page}>
    {toast&&<div className={styles.toast}>{toast}</div>}
    <header className={styles.top}><div><span className={styles.icon}><Icon name="difference" /></span><div><small>COMPANY ADMIN PORTAL</small><h1>Accountant Verification Bridge</h1><p>{admin.name} · {admin.email}</p></div></div><a href={dashboardHref}><Icon name="arrow_back" />Admin dashboard</a></header>

    <article className={styles.panel}><header><h2>Staff documents awaiting Company Admin reference</h2><p>Attach your file or message, then send it to the Accountant for final verification.</p></header><div className={styles.cards}>{data.packets.map((item:any)=>{const current=packetRefs[item.id]??{message:item.adminReferenceMessage||"",url:item.adminReferenceUrl||""};return <article className={styles.card} key={item.id}><header><div><small>{item.kind}</small><strong>{item.staffMessage||"Staff uploaded a file"}</strong></div><span className={`${styles.badge} ${item.status==="VERIFIED"?styles.ok:item.status==="REJECTED"?styles.bad:""}`}>{String(item.status).replaceAll("_"," ")}</span></header><p>Staff file: {item.staffFileUrl||"No file URL"}</p><label className={styles.upload}><Icon name="upload_file" /><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.xls,.xlsx,.doc,.docx" onChange={e=>void fileChange(e.target.files?.[0],item.id,"packet")} />{current.url&&<small>{current.url}</small>}</label><textarea className={styles.reason} placeholder="Company Admin reference message" value={current.message} onChange={e=>setPacketRefs({...packetRefs,[item.id]:{...current,message:e.target.value}})} /><div className={styles.actions}><button disabled={busy} onClick={()=>void act("ADD_VERIFICATION_REFERENCE",{packetId:item.id,adminReferenceMessage:current.message,adminReferenceUrl:current.url})}><Icon name="send" />Send to Accountant</button>{item.staffFileUrl&&<a href={item.staffFileUrl} target="_blank" rel="noreferrer">Open staff file</a>}</div></article>})}{!data.packets.length&&<div className={styles.empty}>No staff verification packets.</div>}</div></article>

    <article className={styles.panel}><header><h2>Company Admin expense decisions</h2><p>The final expense is approved only after Accountant approval too.</p></header><div className={styles.table}><table><thead><tr><th>Expense</th><th>Amount</th><th>Current status</th><th>Reason</th><th>Decision</th></tr></thead><tbody>{data.expenses.map((item:any)=><tr key={item.id}><td><strong>{item.category||item.type||"Expense"}</strong><br />{item.description||item.purpose||"No description"}</td><td>{money(item.amount)}</td><td>{String(item.status||item.approvalStatus||"PENDING")}</td><td><input className={styles.reason} placeholder="Required when rejecting" value={expenseReasons[item.id]||""} onChange={e=>setExpenseReasons({...expenseReasons,[item.id]:e.target.value})} /></td><td><div className={styles.actions}><button disabled={busy} onClick={()=>void act("DECIDE_EXPENSE",{expenseId:item.id,decision:"APPROVE"})}>Approve</button><button className={styles.danger} disabled={busy} onClick={()=>void act("DECIDE_EXPENSE",{expenseId:item.id,decision:"REJECT",reason:expenseReasons[item.id]})}>Reject</button></div></td></tr>)}</tbody></table></div></article>

    <article className={styles.panel}><header><h2>Bank statement references</h2><p>Attach statement values and file for each staff proof before Accountant reconciliation.</p></header><div className={styles.cards}>{data.bankComparisons.map((item:any)=>{const current=bankRefs[item.id]??{adminAmount:item.adminAmount?String(item.adminAmount):"",adminReference:item.adminReference||"",adminDate:item.adminDate?String(item.adminDate).slice(0,10):new Date().toISOString().slice(0,10),adminBankAccount:item.adminBankAccount||"",adminFileUrl:item.adminFileUrl||""};return <article className={styles.card} key={item.id}><header><div><small>STAFF BANK PROOF</small><strong>{item.staffReference||"No reference"} · {money(item.staffAmount)}</strong></div><span className={styles.badge}>{item.accountantDecision}</span></header><div className={styles.form}><div className={styles.pair}><label><span>Statement amount</span><input type="number" min="1" value={current.adminAmount} onChange={e=>setBankRefs({...bankRefs,[item.id]:{...current,adminAmount:e.target.value}})} /></label><label><span>Statement date</span><input type="date" value={current.adminDate} onChange={e=>setBankRefs({...bankRefs,[item.id]:{...current,adminDate:e.target.value}})} /></label></div><label><span>Statement reference</span><input value={current.adminReference} onChange={e=>setBankRefs({...bankRefs,[item.id]:{...current,adminReference:e.target.value}})} /></label><label><span>Bank account</span><input value={current.adminBankAccount} onChange={e=>setBankRefs({...bankRefs,[item.id]:{...current,adminBankAccount:e.target.value}})} /></label><label className={styles.upload}><Icon name="upload_file" /><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.csv,.xls,.xlsx,.doc,.docx" onChange={e=>void fileChange(e.target.files?.[0],item.id,"bank")} />{current.adminFileUrl&&<small>{current.adminFileUrl}</small>}</label><button className={styles.button} disabled={busy} onClick={()=>void act("UPSERT_BANK_REFERENCE",{comparisonId:item.id,depositId:item.depositId,staffId:item.staffId,staffAmount:item.staffAmount,staffReference:item.staffReference,staffDate:item.staffDate,staffBankAccount:item.staffBankAccount,staffFileUrl:item.staffFileUrl,...current})}><Icon name="send" />Send statement to Accountant</button></div></article>})}{!data.bankComparisons.length&&<div className={styles.empty}>No staff bank proofs are waiting.</div>}</div></article>

    <section className={styles.grid}>
      <article className={styles.panel}>
        <header><h2>Register fingerprint device</h2><p>Only Company Admin and Accountant can approve a device gateway.</p></header>
        <form className={styles.form} onSubmit={async event=>{event.preventDefault();const result=await act("REGISTER_DEVICE",device);if(result?.token){await navigator.clipboard?.writeText(result.token).catch(()=>undefined);setToast(`Device token: ${result.token}`);setDevice({name:"",serialNumber:"",locationLabel:""});}}}>
          <label><span>Device name</span><input required value={device.name} onChange={event=>setDevice({...device,name:event.target.value})} placeholder="Main office fingerprint" /></label>
          <div className={styles.pair}><label><span>Serial number</span><input required value={device.serialNumber} onChange={event=>setDevice({...device,serialNumber:event.target.value})} placeholder="ZK-001992" /></label><label><span>Location</span><input value={device.locationLabel} onChange={event=>setDevice({...device,locationLabel:event.target.value})} placeholder="Head office" /></label></div>
          <button className={styles.button} disabled={busy}><Icon name="fingerprint" />Register and generate token</button>
        </form>
      </article>
      <article className={styles.panel}>
        <header><h2>Enrol Staff fingerprint reference</h2><p>Store only the vendor template key; do not upload raw fingerprint images.</p></header>
        <form className={styles.form} onSubmit={async event=>{event.preventDefault();const result=await act("ENROLL_FINGERPRINT",enrollment);if(result)setEnrollment({...enrollment,templateKey:""});}}>
          <label><span>Approved device</span><select required value={enrollment.deviceId} onChange={event=>setEnrollment({...enrollment,deviceId:event.target.value})}><option value="">Select active device</option>{data.devices.filter((item:any)=>item.status==="ACTIVE").map((item:any)=><option key={item.id} value={item.id}>{item.name} · {item.serialNumber}</option>)}</select></label>
          <label><span>Active Staff user</span><select required value={enrollment.staffId} onChange={event=>setEnrollment({...enrollment,staffId:event.target.value})}><option value="">Select Staff</option>{data.staff.map((item:any)=><option key={item.id} value={item.id}>{item.name||item.email} · {item.email}</option>)}</select></label>
          <label><span>Vendor template key</span><input required value={enrollment.templateKey} onChange={event=>setEnrollment({...enrollment,templateKey:event.target.value})} placeholder="vendor-template-28" /></label>
          <button className={styles.button} disabled={busy}><Icon name="person_add" />Save enrolment</button>
        </form>
      </article>
    </section>

    <article className={styles.panel}><header><h2>Approved fingerprint devices</h2><p>Device tokens are shown only once at registration. Company Admin can immediately block a lost or untrusted device.</p></header><div className={styles.table}><table><thead><tr><th>Device</th><th>Serial</th><th>Location</th><th>Status</th><th>Last seen</th><th>Control</th></tr></thead><tbody>{data.devices.map((item:any)=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.serialNumber}</td><td>{item.locationLabel||"—"}</td><td>{item.status}</td><td>{item.lastSeenAt?new Date(item.lastSeenAt).toLocaleString("en-GB"):"Never"}</td><td><div className={styles.actions}><button disabled={busy||item.status==="ACTIVE"} onClick={()=>void act("SET_DEVICE_STATUS",{deviceId:item.id,status:"ACTIVE"})}>Activate</button><button className={styles.danger} disabled={busy||item.status==="BLOCKED"} onClick={()=>void act("SET_DEVICE_STATUS",{deviceId:item.id,status:"BLOCKED"})}>Block</button></div></td></tr>)}</tbody></table></div></article>
  </main>;
}
